name: Gitartwork Contribution Graph
permissions:
  contents: write

on:
  push:

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Generate gitartwork SVG
        uses: jasineri/gitartwork@v1
        with:
          user_name: hamzaali-712
          text: HAMZA ALI

      - name: Push generated artwork
        uses: jasineri/simple-push-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
