name: Gitartwork Contribution Graph

on:
  push:

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate gitartwork SVG
        uses: jasineri/gitartwork@v1
        with:
          user_name: hamzaali-712
          text: HAMZA ALI

      - name: Push generated artwork
        uses: jasineri/simple-push-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
